apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-inventory-worker
  labels:
    name: locust-inventory-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-inventory-worker
  template:
    metadata:
      labels:
        app: locust-inventory-worker
        name: locust-inventory-worker
        role: worker
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: locust-inventory-worker
          image: 10.98.0.201:5000/custom-locust:33 # Locust version
          resources:
            requests:
              cpu: 1
          env:
            - name: LOCUST_LOGLEVEL
              value: "DEBUG"
            - name: LOCUST_MODE_WORKER
              value: "true"
            - name: LOCUST_MASTER_NODE_HOST
              value: locust-inventory-master-service # Master Deployment Name
            - name: LOCUST_LOCUSTFILE
              value: load_generator/locustfiles/hls_player.py
            - name: LOCUST_HOST
              value: "112.121.154.10"
            - name: HOST_PORT
              value: "8182"
            - name: CHANNEL_URI
              value: "live/lx-origin/dooball66-epl1_720"
